export interface Profile{
  id?:number;
  name?:string;
  email?:string;
  password?:string;
  team?:string;
  logged?:boolean;
  win?:number;
  winHistory?:Array<object>,
  draw?:number;
  drawHistory?:Array<object>,
  loss?:number;
  lossHistory?:Array<object>,
  history?:string;
  activeGame?:boolean;
  rival?:string;
  rivalFlag?:string;
  rivalName?:string;
  rivalTeam?:string;
  turn?:boolean;
  half?:number;
  halfDeffend?:number;
  firstHalf?:Array<any>;
  round?:string;
  secondHalf?:number;
  numberOfAction?:number;
  questions?:Array<number>;
  answers?:Array<boolean>;
  goal?:Array<number>;
  quart?:number;
  scoredFirsthalf?:number;
  scoredSecondHalf?:number;
  scoredFirsthalfRival?:number;
  scoredSecondHalfRival?:number;
  lastResult?:any;
  lastHalfResult?:any;
  endMatch?:boolean;
  guest?:boolean;
}
